### ISSUE TITLE
Code samples on Features page have huge font size and break layout.

### ISSUE THREAD

**Issue by GrayFace** [nim-lang/website#44] opened 2017-09-06 11:52 UTC
Here's a screenshot: https://www.dropbox.com/s/kwmqmpczm7dsanm/screenshot.178.png?dl=0

FireFox 47.0.2, 120DPI in system settings.

**Comment by Calinou** [comment] 2017-09-06 14:42
I cannot reproduce this issue in Chromium 60, Firefox 55 and Edge 15 (I'm not using hiDPI on this monitor, but I'm not sure if it's related), however, the font is still really large compared to the code sample at the top of the page:

**The code sample at the bottom of the Features page:**
![Nim website code sample (page bottom)](https://user-images.githubusercontent.com/180032/30117948-041db206-9322-11e7-867c-bf3b0064fde2.png)

**The code sample at the top of the Features page:**
![Nim website code sample (page top)](https://user-images.githubusercontent.com/180032/30117970-14a744b6-9322-11e7-99e1-8e6747126a5b.png)

**Comment by narimiran** [comment] 2019-01-05 12:51
I think that #115 will fix this once is merged.

**Comment by narimiran** [comment] 2019-06-04 11:50
I couldn't reproduce the original example.

> however, the font is still really large compared to the code sample at the top of the page

This seems to be fixed now too.

**Closed by narimiran** 2019-06-04 11:50 UTC
